# Build settings
permalink   : /blog/:year/:title/
markdown    : kramdown
highlighter : rouge
gems: [jekyll-paginate]

paginate: 6
paginate_path: "/blog/page/:num/"
comments: true

source: source
destination: _site
sass:
  sass_dir: _scss
  style: compressed # expanded

# SEO settings
title: Andrej Antaš
description: "My personal pages"
keywords: "Ruby, Ruby on Rails, Andrej, blog, web"
url: http://antas.cz
baseurl: ""

google_analytics: UA-74779905-1
repo: http://github.com/redrick/redrick.github.io
disqus_shortname: "andrejantas"
disqus_site_shortname: "antascz"

# Author settings
author:
  name      : Andrej Antaš
  job       : Ruby on Rails developer
  bio       : "Ruby on Rails developer based in Prague, born in Slovakian mountains spending my time in startups helping amazing stuff happen. Also drinking accessive amounts of coffee through day..."
  thumb     : /images/andrej.jpeg
  email     : andrej@antas.cz
  url       : http://antas.cz
  github    : http://github.com/redrick
  twitter   : http://twitter.com/AndrejAntas
  facebook  : http://facebook.com/redricko
  linkedin  : https://cz.linkedin.com/in/andrejantas

# navbar pages
navbar:
  - slug: about
    title: About
  - slug: cv
    title: CV
  - slug: blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
